# Generated by Django 5.0.1 on 2024-04-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookMng", "0002_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="comments",
            field=models.CharField(default="", max_length=300),
            preserve_default=False,
        ),
    ]
