# Generated by Django 5.0.1 on 2024-04-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookMng", "0003_book_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
