# Generated by Django 5.0.1 on 2024-02-27 04:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookMng", "0002_book"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="publishedate",
            new_name="publishdate",
        ),
    ]
